### ISSUE TITLE
ERROR after modify the platform_def.h

### ISSUE THREAD

**Issue by Chiliad-Spring** [TephrocactusMYC/llama2-optee#2]
After modify the platform_def.h, ERROR occur when I run the qemu

WARNING: Firmware Image Package header check failed.
WARNING: Firmware Image Package header check failed.
WARNING: The load address in optee header 0xe100000 - 0xe188378 is not in reserved area: 0x40100000 - 0x48000000.
WARNING: OPTEE header parse error.
ERROR:   BL2: Failure in post image load handling (-1)

Maybe cause by?
+#define SEC_DRAM_BASE                 0x40100000
+#define SEC_DRAM_SIZE                  0x07f00000

Why this and how to fix it?

**Comment by Chiliad-Spring** [comment]
[Maybe the reason is the file plat-vexpress/conf.mk also need to be modify
Anyway, I modify the mk file, but the new error occur after (qemu) c
I meet the same problem as you met

D/TC:0   core_mmu_xlat_table_alloc:527 xlat tables used 1 / 8
D/TC:0   core_mmu_xlat_table_alloc:527 xlat tables used 2 / 8
D/TC:0   core_mmu_xlat_table_alloc:527 xlat tables used 3 / 8
D/TC:0   core_mmu_xlat_table_alloc:527 xlat tables used 4 / 8
I/TC: 
D/TC:0   carve_out_core_mem:2666 0x40100000 .. 0x40300000
D/TC:0   boot_mem_release_unused:166 Allocated 0 bytes at va 0x40261000 pa 0x40261000
D/TC:0   boot_mem_release_unused:170 Tempalloc 9280 bytes at va 0x402fdbc0
D/TC:0   boot_mem_release_unused:192 Carving out 0x40100000..0x40260fff
D/TC:0   boot_mem_release_unused:201 Releasing 638976 bytes from va 0x40261000
E/TC:0 0 init_external_dt:857 Invalid Device Tree at 0x48000000: error -9
E/TC:0 0 Panic at core/kernel/dt.c:858 <init_external_dt>
E/TC:0 0 TEE load address @ 0x40100000
E/TC:0 0 Call stack:
E/TC:0 0  0x40107dec
E/TC:0 0  0x40115f2c
E/TC:0 0  0x4011214c
E/TC:0 0  0x401077bc
E/TC:0 0 notify_other_cores:43 Can't notify other cores, main interrupt chip not set

https://github.com/OP-TEE/optee_os/issues/6841#issuecomment-2151860541

So can you tell me how do you solved this error at that time?
Besides, I didnt copy any elf-opxxx directory as your Readme said, just use the native optee repo and modify those files

**Comment by TephrocactusMYC** [comment]
> the file plat-vexpress/conf.mk also need to be modify

You are right.

> I modify the mk file, but the new error occur after (qemu) c I meet the same problem as you met
> 
> D/TC:0 core_mmu_xlat_table_alloc:527 xlat tables used 1 / 8 D/TC:0 core_mmu_xlat_table_alloc:527 xlat tables used 2 / 8 D/TC:0 core_mmu_xlat_table_alloc:527 xlat tables used 3 / 8 D/TC:0 core_mmu_xlat_table_alloc:527 xlat tables used 4 / 8 I/TC: D/TC:0 carve_out_core_mem:2666 0x40100000 .. 0x40300000 D/TC:0 boot_mem_release_unused:166 Allocated 0 bytes at va 0x40261000 pa 0x40261000 D/TC:0 boot_mem_release_unused:170 Tempalloc 9280 bytes at va 0x402fdbc0 D/TC:0 boot_mem_release_unused:192 Carving out 0x40100000..0x40260fff D/TC:0 boot_mem_release_unused:201 Releasing 638976 bytes from va 0x40261000 E/TC:0 0 init_external_dt:857 Invalid Device Tree at 0x48000000: error -9 E/TC:0 0 Panic at core/kernel/dt.c:858 <init_external_dt> E/TC:0 0 TEE load address @ 0x40100000 E/TC:0 0 Call stack: E/TC:0 0 0x40107dec E/TC:0 0 0x40115f2c E/TC:0 0 0x4011214c E/TC:0 0 0x401077bc E/TC:0 0 notify_other_cores:43 Can't notify other cores, main interrupt chip not set

Maybe the problem you're encountering can be solved in https://github.com/TephrocactusMYC/llama2-optee/issues/1#issuecomment-2522256656

> 
> [OP-TEE/optee_os#6841 (comment)](https://github.com/OP-TEE/optee_os/issues/6841#issuecomment-2151860541)
> 
> So can you tell me how do you solved this error at that time? Besides, I didnt copy any elf-opxxx directory as your Readme said, just use the native optee repo and modify those files

The solution is in some of the comments further down https://github.com/OP-TEE/optee_os/issues/6841#issuecomment-2188552619

However, I shouldn't be responsible for answering questions related to OP-TEE itself. If you just want to increase secure memory in QEMU, **please ask in the official repository**. You can continue to ask questions in my issue or create a new issue if you're interested.
